"""seven core tables

Revision ID: 91abc355a4df
Revises: 062ea634353c
Create Date: 2026-09-15 22:33:19.921635

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "91abc355a4df"
down_revision: str | Sequence[str] | None = "062ea634353c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "research_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question", sa.String(length=500), nullable=False),
        sa.Column("background", sa.String(length=1000), nullable=True),
        sa.Column("depth", sa.String(length=16), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "paused",
                "done",
                "failed",
                "canceled",
                "stopped",
                name="task_status",
            ),
            nullable=False,
        ),
        sa.Column("thread_id", sa.String(length=64), nullable=True),
        sa.Column("token_budget", sa.Integer(), nullable=False),
        sa.Column("token_used", sa.Integer(), nullable=False),
        sa.Column("cost_cny", sa.Float(), nullable=False),
        sa.Column("error_msg", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("markdown", sa.Text(), nullable=False),
        sa.Column("chart_specs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("token_total", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["research_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reports_task_id"), "reports", ["task_id"], unique=False)
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("domain", sa.String(length=200), nullable=True),
        sa.Column("credibility", sa.Integer(), nullable=True),
        sa.Column("freshness", sa.Float(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["research_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sources_content_hash"), "sources", ["content_hash"], unique=False)
    op.create_index(op.f("ix_sources_task_id"), "sources", ["task_id"], unique=False)
    op.create_table(
        "sub_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("keywords", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "running", "done", "failed", "skipped", name="subtask_status"),
            nullable=False,
        ),
        sa.Column("round_no", sa.Integer(), nullable=False),
        sa.Column("error_msg", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["research_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sub_tasks_task_id"), "sub_tasks", ["task_id"], unique=False)
    op.create_table(
        "agent_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("sub_task_id", sa.Integer(), nullable=True),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "plan",
                "search",
                "fetch",
                "note",
                "reflect",
                "degrade",
                "budget",
                "synthesize",
                "control",
                name="event_type",
            ),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tokens", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sub_task_id"],
            ["sub_tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["research_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_agent_events_payload_gin",
        "agent_events",
        ["payload"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_agent_events_task_id"), "agent_events", ["task_id"], unique=False)
    op.create_index("ix_agent_events_task_seq", "agent_events", ["task_id", "seq"], unique=True)
    op.create_table(
        "eval_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question", sa.String(length=500), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=True),
        sa.Column("coverage", sa.Float(), nullable=False),
        sa.Column("accuracy", sa.Float(), nullable=False),
        sa.Column("citation", sa.Float(), nullable=False),
        sa.Column("judge_model", sa.String(length=64), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_eval_runs_report_id"), "eval_runs", ["report_id"], unique=False)
    op.create_table(
        "notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("sub_task_id", sa.Integer(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sub_task_id"],
            ["sub_tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["research_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notes_source_id"), "notes", ["source_id"], unique=False)
    op.create_index(op.f("ix_notes_sub_task_id"), "notes", ["sub_task_id"], unique=False)
    op.create_index(op.f("ix_notes_task_id"), "notes", ["task_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notes_task_id"), table_name="notes")
    op.drop_index(op.f("ix_notes_sub_task_id"), table_name="notes")
    op.drop_index(op.f("ix_notes_source_id"), table_name="notes")
    op.drop_table("notes")
    op.drop_index(op.f("ix_eval_runs_report_id"), table_name="eval_runs")
    op.drop_table("eval_runs")
    op.drop_index("ix_agent_events_task_seq", table_name="agent_events")
    op.drop_index(op.f("ix_agent_events_task_id"), table_name="agent_events")
    op.drop_index("ix_agent_events_payload_gin", table_name="agent_events", postgresql_using="gin")
    op.drop_table("agent_events")
    op.drop_index(op.f("ix_sub_tasks_task_id"), table_name="sub_tasks")
    op.drop_table("sub_tasks")
    op.drop_index(op.f("ix_sources_task_id"), table_name="sources")
    op.drop_index(op.f("ix_sources_content_hash"), table_name="sources")
    op.drop_table("sources")
    op.drop_index(op.f("ix_reports_task_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_table("research_tasks")
    # ### end Alembic commands ###
