"""add event_seq counter to research_tasks

Revision ID: e19281cc56f4
Revises: 91abc355a4df
Create Date: 2026-09-15 22:40:34.487771

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e19281cc56f4"
down_revision: str | Sequence[str] | None = "91abc355a4df"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "research_tasks", sa.Column("event_seq", sa.Integer(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("research_tasks", "event_seq")
    # ### end Alembic commands ###
